//
//  Place.swift
//  Egyptian Quiz
//
//  Created by Artem Galiev on 04.10.2023.
//

import Foundation
import MapKit

class Place: NSObject, MKAnnotation {
    let title: String?
    let locationName: String?
    let discipline: String?
    let coordinate: CLLocationCoordinate2D
    let id: Int
    let image: String
    let fullDesc: String
    
    init(title: String?, locationName: String?, discipline: String?, coordinate: CLLocationCoordinate2D, id: Int, image: String, fullDesc: String) {
        self.title = title
        self.locationName = locationName
        self.discipline = discipline
        self.coordinate = coordinate
        self.id = id
        self.image = image
        self.fullDesc = fullDesc
        
        super.init()
    }
    
    var subtitle: String? {
        return locationName
    }
}

struct PlaceList {
    var place = [Place(title: "The Great Sphinx", locationName: "A colossal statue", discipline: "The Great Sphinx", coordinate: CLLocationCoordinate2D(latitude: 30.087396, longitude: 31.151086), id: 1, image: NameImage.personOne.rawValue, fullDesc: "The Great Sphinx of Egypt is a colossal statue located in Giza, and it is approximately 4,500 years old. Believed to represent a god with a human head, it was credited to Pharaoh Khafre and is made of limestone. The original name of the Great Sphinx was Sphinkes, and its missing feature is the nose. The purpose of the Great Sphinx is to serve as a guardian monument, and it aligns with the sunrise during the spring equinox, marking the new year in the ancient Egyptian calendar. It is located in close proximity to the Pyramids of Giza and its temple functioned as a place of worship. Erosion caused by wind and sandstorms has affected the Great Sphinx over the centuries, and it symbolizes the union of pharaoh and god in Egyptian mythology. Pharaoh Khafre is associated with its construction, which occurred during the Old Kingdom dynasty."),
                 Place(title: "Book of the dead", locationName: "A book of spells and rituals", discipline: "Book of the dead", coordinate: CLLocationCoordinate2D(latitude: 29.258185, longitude: 31.132668), id: 2, image: NameImage.personTwo.rawValue, fullDesc: "The Book of the Dead is a book of spells and rituals. Its primary purpose in ancient Egypt was to guide the deceased through the afterlife. Another name for the Book of the Dead is The Coffin Texts The ancient Egyptian god prominently featured in the Book of the Dead is Osiris. Copies of the Book of the Dead were typically made on papyrus. They were rolled up and stored in jars in the tombs of the deceased. The central theme of the Book of the Dead is the judgment of the deceased. It emphasizes the concept of ma'at, which underscores the need for ethical behavior and truthfulness. The guardian figure that appears at the gates of the afterlife in the Book of the Dead is called Horus the Avenger. The first spell in the Book of the Dead, often referred to as the Opening of the Mouth ceremony, is Spell 17, and it aims to restore the deceased's ability to speak and eat. Tutankhamun's tomb contained a version of the Book of the Dead, which typically consists of 42 chapters or spells. The purpose of the spells in the Book of the Dead is to protect the deceased in the afterlife. The Weighing of the Heart ceremony in the Book of the Dead represents the judgment of the deceased's actions. Priests were responsible for creating and reciting the spells from the Book of the Dead during burial ceremonies. The boat often depicted in the Book of the Dead symbolizes the journey to the afterlife and is called The Solar Barge. The ultimate goal for the deceased in the afterlife, according to the Book of the Dead, is to achieve eternal life and happiness. The most prolific use and creation of the Book of the Dead occurred during the New Kingdom period of ancient Egyptian history. The Book of the Dead is primarily written in hieroglyphics and survived into modern times in the form of papyrus scrolls."),
                 Place(title: "Isida", locationName: "The goddess of motherhood and magic", discipline: "Isida", coordinate: CLLocationCoordinate2D(latitude: 24.012505, longitude: 32.876938), id: 3, image: NameImage.personThree.rawValue, fullDesc: "Isis in Egyptian mythology is the goddess of motherhood and magic. She is often depicted as wearing a headdress that resembles a serpent. Isis and Osiris in Egyptian mythology are husband and wife. She is known for her role in the resurrection of Osiris. The worship of Isis was closely associated with the ancient Egyptian city of Philae. The symbol commonly associated with Isis, representing her protective and nurturing qualities, is the sistrum, a musical instrument. Isis played a key role in agriculture and fertility in ancient Egyptian life. In the resurrection of Osiris, her role was to retrieve his missing body parts. Isis was often invoked for her protection and guidance during the death of individuals in ancient Egypt. She is often given the title The Divine Mother due to her maternal and nurturing qualities. The sacred animal associated with Isis is the cow. When depicted with her wings outstretched in Egyptian art, it symbolizes her association with the sky and heavens. Isis used the magical spell known as the Spell of Isis to resurrect Osiris. She was also associated with the annual flooding of the Nile River and protected the crops from flooding. Isis is often equated with the Greek goddess Demeter due to their similar attributes and roles. The sistrum, a musical instrument, was used in the worship of Isis to ward off evil spirits. The Isis Throne symbolizes her divine authority and motherhood. Augustus (Octavian) was associated with the worship of Isis during the Roman Empire. Hathor, in some Egyptian myths, was the sister and protector of Isis. Isis is often depicted nursing her son, Horus, in the form of a cow. Priests and priestesses dedicated to the worship of Isis in ancient Egypt were caretakers of temple rituals."),
                 Place(title: "Anubis", locationName: "The god of death and mummification", discipline: "Anubis", coordinate: CLLocationCoordinate2D(latitude: 24.977947, longitude: 32.873105), id: 4, image: NameImage.personFour.rawValue, fullDesc: "Anubis in Egyptian mythology is the god of death and mummification. His primary role in Egyptian mythology is to guide souls to the afterlife. Anubis is usually depicted in ancient Egyptian art as a jackal-headed god. He was closely associated with mummification and the afterlife in the ancient Egyptian religion. In the mummification process, Anubis played the role of embalming the body. He also had a significant role in the weighing of the heart ceremony in ancient Egyptian funerary practices, where he balanced the scales. Anubis took the form of a jackal in ancient Egyptian beliefs, symbolizing the wild and unpredictable nature of death. Images or statues of Anubis were often placed by the entrance to tombs. He is often associated with Osiris as a guide to the afterlife. The significance of Anubis' jackal form in ancient Egyptian culture lies in symbolizing the unpredictable nature of death. The sacred embalming tool associated with Anubis is the Scepter of Anubis. He preserved the organs removed during the mummification process in canopic jars. Anubis was closely associated with the city of Abydos, where he served as the protector of royal tombs. Besides his role in the afterlife, Anubis was believed to oversee justice and judgment in human existence. The Opening of the Mouth ceremony in ancient Egyptian funerary practices served to restore the deceased's ability to speak and eat. Anubis played a role in providing protection during this ceremony. In some ancient Egyptian myths, Anubis was considered the son of Osiris. The papyrus scroll that contains the spells and rituals for the Opening of the Mouth ceremony is known as The Book of the Dead. Thoth is often depicted alongside Anubis in ancient Egyptian art and mythology. During the funeral procession of a deceased individual, Anubis primarily guided the deceased's soul to the tomb."),
                 Place(title: "Taweret", locationName: "The goddess of fertility and childbirth", discipline: "Taweret", coordinate: CLLocationCoordinate2D(latitude: 27.933278, longitude: 30.145998), id: 5, image: NameImage.personFive.rawValue, fullDesc: "Taweret in Egyptian mythology is the goddess of fertility and childbirth. Her primary role in Egyptian mythology is to safeguard pregnant women and children. Taweret is typically depicted in ancient Egyptian art as a hippopotamus-headed goddess. She is closely associated with childbirth and motherhood in ancient Egyptian society. Pregnant women and mothers in ancient Egypt revered Taweret because she safeguarded them and their children from harm. As a protective goddess, Taweret represented the nurturing and protective force of nature. The amulet associated with Taweret and believed to bring protection to pregnant women and children is called the Bes Pendant. Isis, another Egyptian goddess, shares similarities with Taweret in her protective role over childbirth and motherhood. Taweret's distinctive features include a hippopotamus head and a human body. Besides her protective role, Taweret was believed to influence harmony and balance in human life. In the context of childbirth, Taweret was invoked for a safe delivery. She was often depicted holding the ankh, a symbol representing life and protection. Taweret's paw on a magical knot symbolized the binding of chaos and disorder. In the cosmic order of the universe, Taweret maintained the balance between chaos and order. Taweret was sometimes associated with Hathor, another goddess of childbirth, and was honored with the Feast of Taweret in ancient Egypt. The god Bes, often associated with music and dance, was sometimes depicted with Taweret in certain contexts. Taweret protected the wearer from the evil eye in relation to the magical amulet known as the 'wedjat' or 'Eye of Horus.'In addition to childbirth, Taweret protected people from warfare and conflict in ancient Egyptian belief. The hieroglyphic symbol associated with Taweret and childbirth and protection is the 'Sema' sign."),
                 Place(title: "Nefertiti", locationName: "A queen and wife of Pharaoh Akhenaten", discipline: "Nefertiti", coordinate: CLLocationCoordinate2D(latitude: 22.339086, longitude: 31.624291), id: 6, image: NameImage.personSix.rawValue, fullDesc: "Nefertiti in ancient Egypt was a queen and the wife of Pharaoh Akhenaten. She is best known for her association with Pharaoh Akhenaten, with the English translation of her name being The Beautiful One Has Come. Nefertiti and Akhenaten brought a religious revolution to Egypt, introducing monotheism and worshipping only one god, Aten. They established a new capital city, Amarna, during their reign. Nefertiti is often depicted in art wearing the distinctive Nemes headdress. She and Akhenaten had six daughters. Evidence of Nefertiti's beauty and grace can be found in numerous statues and busts depicting her. After her disappearance from historical records, her daughter Meritaten succeeded her as queen. The modern location of the ancient city of Akhetaten (Amarna) is Minya. In addition to her role as queen, Nefertiti held the title of High Priestess of Hathor. The famous artifact featuring a bust of Nefertiti is called The Nefertiti Bust and is displayed in a Berlin museum. Co-regent Pharaoh Ay may have ruled alongside Nefertiti and later succeeded her. Nefertiti's title Great Royal Wife signifies her position as the chief queen and wife of the pharaoh. After the religious reforms of Akhenaten and Nefertiti, their images and inscriptions were often destroyed and defaced. One commonly suggested theory regarding Nefertiti's fate is that she changed her name and identity. Nefertiti's daughter, Ankhesenamun, is believed to have been the mother of the famous pharaoh Tutankhamun. She is often compared to Queen Hatshepsut in terms of influence and historical significance. Nefertiti is associated with the artistic and cultural period known as the New Kingdom in ancient Egypt. The ancient Egyptian god associated with Nefertiti and Akhenaten's reign was Aten."),
                 Place(title: "Sekhmet", locationName: "The goddess of war and destruction", discipline: "Sekhmet", coordinate: CLLocationCoordinate2D(latitude: 24.574082, longitude: 29.791347), id: 7, image: NameImage.personSeven.rawValue, fullDesc: "Sekhmet in Egyptian mythology is the goddess of war and destruction, primarily responsible for unleashing her wrath and punishing humanity. She is typically depicted as a lioness-headed goddess in ancient Egyptian art. Sekhmet was associated with health and healing in Egyptian society and religion, often invoked for protection against plagues and diseases. In maintaining cosmic balance, she prevented chaos and disorder. Sekhmet's association with healing and medicine is symbolized by the caduceus. Similar to her lioness form and protective role, the goddess Bastet shares similarities with Sekhmet. The festival held in honor of Sekhmet in ancient Egypt, often involving music, dance, and offerings, is called The Feast of Sekhmet. To prevent Sekhmet from destroying humanity, the offering of beer dyed red to resemble blood was made. Sekhmet's manifestations as a healer and destroyer were known as her two faces. The magical potion offered to her to pacify her and avert her wrath was called the Beer of the Sun. In battle, she is associated with the Eye of Ra. Apart from her protective role, Sekhmet was believed to influence justice and judgment. The ancient Egyptian text that contains spells and rituals for healing and protection, often invoking Sekhmet, is The Book of the Dead. Sekhmet is associated with Ra due to her destructive nature, and her lioness form emphasizes her fierce and destructive side. The red color associated with Sekhmet symbolizes the fiery aspects of her nature. She is often considered the daughter of Ra, and her title as The Eye of Ra symbolizes her role in maintaining the cosmic order."),
                 Place(title: "Ra", locationName: "The god of the sun", discipline: "Ra", coordinate: CLLocationCoordinate2D(latitude: 25.720125, longitude: 32.654910), id: 8, image: NameImage.personEight.rawValue, fullDesc: "Ra, the god of the sun in Egyptian mythology, holds the primary role of bringing light and warmth to the world. He is typically depicted as a falcon-headed god and is associated with the sun's cycles. Ra's daily journey across the sky marks the passage of time and seasons, and he defeats the mythical serpent Apep each night during his journey through the underworld. Agriculture and harvest were closely associated with Ra, and his symbol, the 'ankh,' represents life and immortality. The sacred beetle associated with Ra and the sun is the Scarab, and his primary cult center is Heliopolis. The 'Udjat eye' is the protective amulet featuring the Eye of Ra, and Ra brought creation into being by speaking it into existence. The Coronation ritual is performed by the pharaoh to establish a divine connection with Ra. Ra is associated with the midday sun at its zenith, and Nut is the goddess who swallows the sun at night. His association with the hawk or falcon represents his ability to see all things, and his journey through the afterlife is known as the Solar Duat. Khnum represents Ra's creative power, and the ancient Egyptian text containing Ra's rituals is the Pyramid Texts. Ra's role as the sun god signifies bringing light, warmth, and life to the world."),
                 Place(title: "Horus", locationName: "The god of war and protection", discipline: "Horus", coordinate: CLLocationCoordinate2D(latitude: 26.007590, longitude: 31.044304), id: 9, image: NameImage.personNine.rawValue, fullDesc: "Horus, the falcon-headed god in Egyptian mythology, embodies the roles of war and protection, symbolizing majesty and power. His rivalry with his uncle Set over the pharaoh's throne is central to Egyptian mythology, and he plays a crucial role in defending Egypt from chaos. Horus is often associated with the 'Eye of Horus,' representing protection and healing, and the 'Wedjat' amulet, signifying safe passage to the afterlife. In the myth of Osiris, he defeats Set and claims the throne, and the pharaoh is considered the mortal form of Horus on Earth, inheriting divine authority. The 'Crook and Flail' are symbols of his power, and there's a major festival dedicated to him known as the 'Festival of Horus.' Horus has dual aspects: 'Horus the Elder' and 'Horus the Younger,' representing his warrior and protective roles. The unity of Horus and Set is symbolized by the 'Djed Pillar.' Besides protection, Horus also controls the Nile's flooding and guides souls to the underworld."),
                Place(title: "Pyramids of Giza", locationName: "The Pyramids of Giza", discipline: "Pyramids of Giza", coordinate: CLLocationCoordinate2D(latitude: 29.948120, longitude: 31.440532), id: 10, image: NameImage.pyramid.rawValue, fullDesc: "The Pyramids of Giza are one of the most famous and significant landmarks in the world. Here are some key facts and information about the Pyramids of Giza:\n\nThe Pyramids of Giza are located on a rocky plateau on the west bank of the Nile River near Al-Jizah (Giza), northern Egypt. They were erected during the 4th dynasty of the Old Kingdom, circa 2575–c. 2465 \n\nThe Giza pyramid complex consists of three primary pyramids, which were built over the span of three generations by the rulers Khufu, Khafre, and Menkaure. Each pyramid was part of a royal mortuary complex that also included a temple at its base and a long stone causeway leading east from the plateau to a valley temple on the edge of the floodplain\n\nThe Great Pyramid of Giza is the largest and most famous of the three pyramids. It was built by Pharaoh Khufu and is the oldest of the Seven Wonders of the Ancient World. It stands at 146.6 meters (481 feet) tall and was the world's tallest human-made structure for more than 3,800 years.\n\nThe Great Pyramid of Giza is made of limestone, mortar, and granite. Its core is made of yellowish limestone blocks, the outer casing (now almost completely gone) and the inner passages are of finer light-colored limestone, and the interior burial chamber is built of huge blocks of granite.\n\nThe Pyramids of Giza were built as tombs for the pharaohs and their consorts. They were filled with all the things each ruler would need to guide and sustain himself in the next world.\n\nThe ancient engineering feats at Giza were so impressive that even today scientists can't be sure how the pyramids were built. Yet they have learned much about the people who built them and the political power necessary to make it happen.\n\nThe Pyramids of Giza are part of the UNESCO World Heritage Site Memphis and its Necropolis. They are not immutable and will need sufficient attention and protection if they are to remain intact as key touchstones of ancient history."),
                 Place(title: "Pyramids of Djosero", locationName: "The Pyramid of Djoser", discipline: "Pyramids of Djosero", coordinate: CLLocationCoordinate2D(latitude: 29.687144, longitude: 31.375067), id: 11, image: NameImage.pyramid.rawValue, fullDesc: "The Pyramid of Djoser, also known as the Step Pyramid of Djoser, is an archaeological site located in the Saqqara necropolis, Egypt, northwest of the ruins of Memphis. It is the earliest colossal stone building in Egypt and was built in the 27th century BC during the Third Dynasty for the burial of Pharaoh Djoser. Here are some key facts and information about the Pyramid of Djoser: The pyramid is a 6-tier, 4-sided structure that is the central feature of a vast mortuary complex in an enormous courtyard surrounded by ceremonial structures and decoration.The pyramid was designed by Djoser's vizier Imhotep, who is credited with the design and construction of the complex, although the Dynastic Egyptians themselves did not credit him as such.The pyramid is made of limestone, and its substructure lay in a 4 m (13 ft) deep rectangular pit, with mudbrick walls rising to 6 m (20 ft). Three sides were extended and built out to create eight shallow steps rising at an angle of 49°."),
                 Place(title: "The White Desert", locationName: "The White Desert is a national park", discipline: "The White Desert", coordinate: CLLocationCoordinate2D(latitude: 27.346623, longitude: 28.304835), id: 12, image: NameImage.pyramid.rawValue, fullDesc: "The White Desert is a national park located in the Farafra depression in the Sahara Desert, Egypt. Here is some information about the White Desert based on the search results: The White Desert National Park is located in the Farafra depression, 45 km north of the town of Qsar El Farafra. It covers an area of 115.8 square miles (300 sq km) and was first established as a protected area in 2002The White Desert is part of the Farafra depression in the Sahara Desert and features the Farafra Oasis, the Ain El Maqfi Oasis, and the Ain El Wadi Oasis. The park is renowned for the white sands, white sand rock formations, and the introduction to the Great Sand Sea The White Desert is the site of large white chalk rock formations, created through erosion by wind and sand. It is also the site of cliffs, sand dunes, as well as Wadi Hennis and oases at Ain El Maqfi and Ain El Wadi. The highest point in the park is at El Qess Abu Said at 353 m (1,158 ft) above sea level, and the lowest is at Wadi Hennis at 32 m (105 ft). The White Desert is a unique place, and nothing like this can be found anywhere else in the world. It has a white color due to rock formations that make up a bizarre contrast with the yellow desert sand. The road to the White Desert takes about 4 hours. The White Desert is a popular tourist destination, and visitors can take a 12-day excursion that travels through the White Desert, Black Desert, and Crystal Mountain. The excursion allows visitors to experience many different facets of the world's largest desert. The White Desert is also home to various animals, including the endangered Rhim gazelle and the vulnerable Dorcas gazelle, as well as Barbary sheep, jackals, Rüppell's, red and fennec foxes, and the sand cat"),
                 Place(title: "The Black Desert", locationName: "The Black Desert is a region of volcano-shaped and widely spaced mounds.", discipline: "The Black Desert", coordinate: CLLocationCoordinate2D(latitude: 28.132673, longitude: 28.804046), id: 13, image: NameImage.pyramid.rawValue, fullDesc: "The Black Desert is a region of volcano-shaped and widely spaced mounds, distributed along about 30 km (19 mi) in western Egypt between the White Desert in the south and the Bahariya Oasis in the north Most of its mounds are capped by basalt sills, giving them the characteristic black color. The mounds of the Black Desert, up to 100 meters (328 feet) high, vary in size, composition, height, and shape as some are dark consisting of iron quartzite while others are more reddish as its surface rocks consist of iron sandstone. The Black Desert was formed as a result of ancient volcanic activity in the area, and it is located near the Bahariya Oasis, a little north of the White Desert. The Black Desert is a popular stop-off for tours running out of Bahariya Oasis and is usually combined with a White Desert tour. Visitors can climb most of the hills in the Black Desert, and the highest point is the English Mountain, which is the most popular spot for tourists to go up and marvel at the view. The Black Desert has been declared a natural reserve as of 2010 after discovering a large dinosaur skeleton on its borders")
        ]
}

enum AnnotationTitle: String {
    case theGreatSphinx = "The Great Sphinx"
    case bookOfTheDead = "Book of the dead"
    case isida = "Isida"
    case anubis = "Anubis"
    case taweret = "Taweret"
    case nefertiti = "Nefertiti"
    case sekhmet = "Sekhmet"
    case ra = "Ra"
    case gore = "Horus"
    case pyramidsOfGiza = "Pyramids of Giza"
    case pyramidsOfDjosero = "Pyramids of Djosero"
    case theWhiteDesert = "The White Desert"
    case theBlackDesert = "The Black Desert"
    case standardQuestion = "standardQuestion"
}
